### ISSUE TITLE
Issue 7 - The application crashed

### ISSUE THREAD

**Issue by dan301290** [dan301290/Test#7]
Desc: The application crashed when I tried to do "a", "b" and "c"Also "d" is a problem aswellThe problem is with:File: https://github.com/dan301290/Test / tree/master/Repository is Empty

Problem solved
Method: FileOpen()
Line: 23-27

**Comment by dan301290** [comment]
IssueUpdatedBy : dan301290 on : 01/01/2017

**Comment by DanielNuttall** [comment]
I will look into this. I think the problem is in 
File: https://github.com/dan301290/Test/tree/master/Repository is Empty

**Comment by DanielNuttall** [comment]
IssueUpdatedBy : DanielNuttall on : 01/01/2017

**Comment by DanielNuttall** [comment]
I have fixed the issue.

**Comment by DanielNuttall** [comment]
IssueUpdatedBy : DanielNuttall on : 01/01/2017
